version: '3'
services:
  lk-sanmark-eupheme-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - ./src/.env
    image: lk-sanmark-eupheme-dev
    ports:
      - 80:80
    volumes:
      - ./src:/app
